window.LUMIERE_DATA = {
  meta: {
    salon: "Lumiere",
    currency: "ARS",
    today: "2026-08-13",
    weekStart: "2026-08-10",
    weekEnd: "2026-08-15",
    closedDays: [0]
  },

  settings: {
    openTime: "08:00",
    closeTime: "21:00",
    closedDays: [0],
    nightCloseEnabled: false,
    lowStockDefault: 5,
    receptionistSections: ["today", "appointments", "checkout", "clients", "staff", "services", "products", "sales"],
    predefinedRules: [
      { key: "no_show_fee",    label_en: "Charge 50% on no-shows",            label_es: "Cobrar 50% por ausencia",       enabled: true },
      { key: "retouch_free",   label_en: "Free retouch within 7 days",        label_es: "Retoque gratis dentro de 7 días", enabled: false },
      { key: "member_discount",label_en: "Members get 10% off products",      label_es: "Socios 10% de descuento en productos", enabled: true },
      { key: "voucher_cap",    label_en: "Vouchers cover max 50% of bill",    label_es: "Los cupones cubren máx. 50% de la cuenta", enabled: false }
    ],
    customRules: [
      { name: "Loyalty points per ARS spent", value: "1 point per 100 ARS", enabled: true },
      { name: "Welcome gift",                value: "Free lash lift on 3rd visit", enabled: false }
    ]
  },

  i18n: {
    en: {
      role_owner: "Owner", role_admin: "Administrator", role_administrator: "Administrator", role_receptionist: "Receptionist",
      tab_today: "Today", tab_week: "Week", tab_month: "Month",
      today_sales: "Today's sales", tickets: "Visits today", revenue: "Revenue",
      revenue_ars: "Revenue (ARS)", products_sold: "Products sold",
      new_clients: "New clients", returning_clients: "Returning clients", no_shows: "No-shows",
      payments: "Payments", cash: "Cash", card: "Card", mobile: "Mobile payment",
      gift_card: "Gift card", voucher: "Voucher", total: "Total", pending: "Pending",
      weekly_revenue: "Weekly revenue", monthly_revenue: "Monthly revenue",
      service_mix: "Service mix", staff_performance: "Staff performance",
      stock_movement: "Stock movement", top_clients: "Top clients",
      gender_segments: "Men vs women", retention_rate: "Retention rate",
      seasonality: "Seasonality", commission_totals: "Commission totals",
      returning_after_1_2_months: "Returning after 1 / 2 months",
      new_visits: "New", return_visits: "Returning", services: "Services",
      payment_split: "Payment split", week_label: "Week",
      mens: "Men", womens: "Women", women: "Women", men: "Men", morning: "Morning", afternoon: "Afternoon", refresh: "Refresh", close: "Close",
      sec_today: "Today", sec_week: "Week", sec_month: "Month",
      sec_appointments: "Appointments", sec_checkout: "Checkout", sec_clients: "Clients",
      sec_staff: "Staff", sec_services: "Services", sec_products: "Products",
      sec_sales: "Sales", sec_commission: "Commission", sec_reports: "Reports",
      sec_analytics: "Analytics", sec_rules: "Business rules",
      new_appointment: "New appointment", client: "Client", select_client: "Select client",
      add_service: "Add service", add_product: "Add product", add: "Add", bill: "Bill",
      no_lines: "No lines yet", insufficient: "Payment is less than the total",
      complete_payment: "Complete payment", saved: "Ticket saved", low: "Low stock", ok: "OK",
      demo_new_appt: "This demo shows booked appointments; booking is saved locally in the records.",
      commission_owner_note: "Commission rates are set per staff member by the owner/administrator. Receptionists never see this screen.",
      role_stylist: "Stylist", role_assistant: "Assistant", staff: "Staff",
      group_hair: "Hair", group_nails: "Nails", group_beauty: "Beauty",
      time: "Time", status: "Status",
      search: "Search", add_new: "Add new", edit: "Edit", save: "Save", cancel: "Cancel",
      delete: "Delete", name: "Name", group: "Group", price: "Price ARS",
      stock: "Stock", reorder: "Reorder at", gender: "Line", phone: "Phone",
      role: "Role", shift: "Shift",
      add_client: "Add client", add_staff: "Add staff member",
      btn_new_service: "New service", btn_new_product: "New product",
      client_search_ph: "Search by name or ID...", saved_changes: "Changes saved",
      daily: "Daily", weekly: "Weekly", monthly: "Monthly",
      revenue_over_time: "Revenue over time", tickets_over_time: "Visits over time",
      top_services: "Top services", top_products: "Top products", appointments_chart: "Appointments",
      business_rules: "Business rules", operating_hours: "Operating hours",
      open_time: "Opens at", close_time: "Closes at", closed_days: "Closed days",
      night_close: "Auto-close at night",
      night_close_desc: "Show a closed screen outside opening hours",
      custom_rules: "Custom rules", add_rule: "Add rule", rule_name: "Rule name",
      rule_value: "Value", enabled: "Enabled", closed_screen: "We are closed",
      opens_at: "Opens at", now_open: "Open", now_closed: "Closed",
      force_open: "Open now (owner)", reset_bypass: "Restore schedule",
      commission_edit_note: "Edit each staff member's rates below, then save.",
      analytics_note: "Charts are built from your local records. Switch the period for daily, weekly or monthly views.",
      monday: "Mon", tuesday: "Tue", wednesday: "Wed", thursday: "Thu", friday: "Fri", saturday: "Sat", sunday: "Sun",
      visits: "Visits", avg_ticket: "Avg ticket", mon: "Mon", tue: "Tue", wed: "Wed", thu: "Thu", fri: "Fri", sat: "Sat", sun: "Sun",
      clients_editable_note: "Receptionists may add new clients; editing and deleting are for the owner/administrator.",
      biz_health: "Business Health", revenue_analytics: "Revenue Analytics", client_analytics: "Client Analytics",
      staff_analytics: "Staff Analytics", portfolio_analytics: "Services & Products", ops_analytics: "Operations",
      new_vs_returning: "New vs returning clients", returning_rate: "Returning rate", no_show_rate: "No-show rate",
      commission_owed: "Commission owed", avg_frequency: "Avg visits / client", frequency_dist: "Visit frequency",
      top_products_rev: "Top products by revenue", units_sold: "Units sold", revenue_weekday: "Revenue by weekday",
      revenue_heatmap: "Revenue heatmap by week", appt_outcomes: "Appointment outcomes", client_acquisition: "New client acquisition",
      retention_1_2m: "Clients returning after 1-2 months", commission_by_staff: "Commission by staff",
      revenue_by_staff: "Revenue by stylist", visits_by_staff: "Visits by stylist", staff_rev_share: "Revenue share",
      avg_ticket_trend: "Average ticket trend", best_clients: "Top clients by spend", unit: "Units",
      done: "Done", booked: "Booked", export_csv: "Export CSV", from_records: "Built from your local records",
      weekday: "Weekday", week: "Week", n_clients: "Clients", revenue_trend: "Revenue trend", conversion: "Appointment conversion",
      analytics_builder: "Custom analytics builder",
      analytics_builder_note: "Build your own charts on the fly: pick a metric, group it, compare, filter and choose the chart. Save any query you want to keep.",
      query_result: "Query result", saved_queries: "Saved custom queries", run: "Run",
      save_query: "Save query", clear_all: "Clear all saved", no_results: "No data matches this query",
      no_saved_queries: "No saved queries yet. Build one above and press Save query.",
      top_n: "Top N rows", export_result: "Export result",
      metric: "Metric", group_by: "Group by", compare: "Compare", chart_type: "Chart", period: "Period",
      filter_staff: "Stylist filter", filter_gender: "Gender filter", filter_payment: "Payment filter", filter_none: "All",
      metric_revenue: "Revenue", metric_visits: "Visits", metric_avg_ticket: "Avg ticket",
      metric_returning: "Returning visits", metric_new_clients: "New clients",
      metric_product_qty: "Products sold", metric_commission: "Commission",
      dim_day: "Day", dim_week: "Week", dim_month: "Month", dim_weekday: "Weekday",
      dim_staff: "Stylist", dim_service: "Service", dim_product: "Product",
      dim_payment: "Payment", dim_gender: "Gender", dim_client: "Client",
      compare_none: "No comparison", compare_new_ret: "New vs returning",
      compare_payment: "By payment", compare_gender: "By gender", compare_staff: "By stylist",
      compare_group: "By service group",
      chart_auto: "Auto", chart_bars: "Bars", chart_line: "Line", chart_donut: "Donut",
      chart_bars_h: "Horizontal bars", chart_heatmap: "Heatmap (weekday x week)",
      period_all: "All records", period_custom: "Custom range", from_date: "From", to_date: "To",
      custom_range_note: "Analytics are grouped by day (up to 45 days) or by week for longer ranges.",
      starter_packs: "Starter packs", all_packs: "All packs", other: "Other",
      sec_data: "Data & backup",
      data_note: "Export, import and manage your local records.",
      data_backup: "Backup", data_backup_desc: "Download all records as a JSON file you can restore later.",
      data_restore: "Restore", data_import_hint: "Pick a previously downloaded backup file and restore it.",
      data_pick_file: "Pick a backup file first", data_bad_file: "That file is not a valid Lumiere backup",
      data_restored: "Backup restored", data_reset: "Reset to demo data",
      data_reset_desc: "Discard all current data and restore the original demo dataset.",
      data_reset_confirm: "This will erase all current records. Continue?",
      data_export_md: "Export records (Markdown)",
      data_export_clients: "Clients CSV", data_export_staff: "Staff CSV", data_export_products: "Products CSV",
      appt_date: "Date", appt_total: "Total",
      appt_status_noshow: "No-show", appt_status_cancelled: "Cancelled",
      appt_need_date_time: "Pick a date and a time", appt_outside_hours: "Outside opening hours",
      appt_conflict: "That time is already booked for this stylist",
      today_schedule: "Today's schedule", reorder_list: "Reorder list", restock: "Restock",
      sec_care: "Client care",
      care_note: "Re-engagement, no-show watchlist and your most valuable clients.",
      care_due_title: "Due for a visit", care_last_visit: "Last visit", care_days_since: "Days since",
      care_none_due: "Everyone visited recently",
      care_noshow_title: "No-show watchlist", care_noshows: "No-shows", care_none_noshow: "No no-shows recorded",
      care_vip_title: "VIP clients",
      metric_services_rev: "Services revenue", metric_products_rev: "Products revenue",
      metric_returning_rate: "Returning rate", metric_avg_frequency: "Avg visits / client",
      receptionist_access: "Receptionist access",
      receptionist_access_note: "Choose which sections receptionists can open.",
      delete_confirm: "Delete this item?", deleted: "Deleted",
      restocked: "Stock updated", data_reset_done: "Demo data restored",
      nl_title: "Ask a question", nl_placeholder: 'e.g. "Revenue by service this month"',
      nl_run: "Ask", nl_mic: "Voice", nl_listening: "Listening...",
      nl_voice_unsupported: "Voice input not supported in this browser",
      nl_error: "Could not start voice input",
      nl_unknown: "I couldn't understand that. Try one of these:",
      nl_today: "today", nl_from_to: "from {from} to {to}"
    },
    es: {
      role_owner: "Dueño", role_admin: "Administrador", role_administrator: "Administrador", role_receptionist: "Recepcionista",
      tab_today: "Hoy", tab_week: "Semana", tab_month: "Mes",
      today_sales: "Ventas de hoy", tickets: "Visitas de hoy", revenue: "Ingresos",
      revenue_ars: "Ingresos (ARS)", products_sold: "Productos vendidos",
      new_clients: "Clientes nuevos", returning_clients: "Clientes que regresan", no_shows: "Ausencias",
      payments: "Pagos", cash: "Efectivo", card: "Tarjeta", mobile: "Pago móvil",
      gift_card: "Tarjeta de regalo", voucher: "Cupón", total: "Total", pending: "Pendiente",
      weekly_revenue: "Ingresos semanales", monthly_revenue: "Ingresos mensuales",
      service_mix: "Combinación de servicios", staff_performance: "Desempeño del equipo",
      stock_movement: "Movimiento de stock", top_clients: "Mejores clientes",
      gender_segments: "Hombres vs mujeres", retention_rate: "Tasa de retención",
      seasonality: "Estacionalidad", commission_totals: "Totales de comisiones",
      returning_after_1_2_months: "Regresa a los 1 / 2 meses",
      new_visits: "Nuevos", return_visits: "Regresan", services: "Servicios",
      payment_split: "Desglose de pagos", week_label: "Semana",
      mens: "Hombres", womens: "Mujeres", women: "Mujeres", men: "Hombres", morning: "Mañana", afternoon: "Tarde", refresh: "Actualizar", close: "Cerrar",
      sec_today: "Hoy", sec_week: "Semana", sec_month: "Mes",
      sec_appointments: "Turnos", sec_checkout: "Cobro", sec_clients: "Clientes",
      sec_staff: "Equipo", sec_services: "Servicios", sec_products: "Productos",
      sec_sales: "Ventas", sec_commission: "Comisiones", sec_reports: "Informes",
      sec_analytics: "Analíticas", sec_rules: "Reglas del negocio",
      new_appointment: "Nuevo turno", client: "Cliente", select_client: "Seleccionar cliente",
      add_service: "Agregar servicio", add_product: "Agregar producto", add: "Agregar", bill: "Cuenta",
      no_lines: "Sin líneas aún", insufficient: "El pago es menor al total",
      complete_payment: "Completar pago", saved: "Ticket guardado", low: "Stock bajo", ok: "OK",
      demo_new_appt: "Esta demo muestra turnos reservados; la reserva se guarda localmente en los registros.",
      commission_owner_note: "Las comisiones se fijan por integrante por el dueño/administrador. La recepción nunca ve esta pantalla.",
      role_stylist: "Estilista", role_assistant: "Asistente", staff: "Equipo",
      group_hair: "Cabello", group_nails: "Uñas", group_beauty: "Belleza",
      time: "Hora", status: "Estado",
      search: "Buscar", add_new: "Agregar nuevo", edit: "Editar", save: "Guardar", cancel: "Cancelar",
      delete: "Eliminar", name: "Nombre", group: "Grupo", price: "Precio ARS",
      stock: "Stock", reorder: "Reponer en", gender: "Línea", phone: "Teléfono",
      role: "Rol", shift: "Turno",
      add_client: "Agregar cliente", add_staff: "Agregar integrante",
      btn_new_service: "Nuevo servicio", btn_new_product: "Nuevo producto",
      client_search_ph: "Buscar por nombre o ID...", saved_changes: "Cambios guardados",
      daily: "Diario", weekly: "Semanal", monthly: "Mensual",
      revenue_over_time: "Ingresos en el tiempo", tickets_over_time: "Visitas en el tiempo",
      top_services: "Servicios principales", top_products: "Productos principales", appointments_chart: "Turnos",
      business_rules: "Reglas del negocio", operating_hours: "Horario de atención",
      open_time: "Abre a las", close_time: "Cierra a las", closed_days: "Días cerrados",
      night_close: "Cierre automático de noche",
      night_close_desc: "Mostrar pantalla de cerrado fuera del horario",
      custom_rules: "Reglas personalizadas", add_rule: "Agregar regla", rule_name: "Nombre de la regla",
      rule_value: "Valor", enabled: "Activa", closed_screen: "Estamos cerrados",
      opens_at: "Abre a las", now_open: "Abierto", now_closed: "Cerrado",
      force_open: "Abrir ahora (dueño)", reset_bypass: "Restaurar horario",
      commission_edit_note: "Edita los porcentajes de cada integrante y luego guarda.",
      analytics_note: "Los gráficos se generan con tus registros locales. Cambia el período para ver diario, semanal o mensual.",
      monday: "Lun", tuesday: "Mar", wednesday: "Mié", thursday: "Jue", friday: "Vie", saturday: "Sáb", sunday: "Dom",
      visits: "Visitas", avg_ticket: "Ticket promedio", mon: "Lun", tue: "Mar", wed: "Mié", thu: "Jue", fri: "Vie", sat: "Sáb", sun: "Dom",
      clients_editable_note: "La recepción puede agregar clientes; editar y eliminar es del dueño/administrador.",
      biz_health: "Salud del negocio", revenue_analytics: "Análisis de ingresos", client_analytics: "Análisis de clientes",
      staff_analytics: "Análisis del equipo", portfolio_analytics: "Servicios y productos", ops_analytics: "Operación",
      new_vs_returning: "Clientes nuevos vs recurrentes", returning_rate: "Tasa de reincidencia", no_show_rate: "Tasa de ausencias",
      commission_owed: "Comisiones a pagar", avg_frequency: "Visitas promedio / cliente", frequency_dist: "Frecuencia de visitas",
      top_products_rev: "Productos por ingresos", units_sold: "Unidades vendidas", revenue_weekday: "Ingresos por día",
      revenue_heatmap: "Mapa de calor semanal", appt_outcomes: "Resultado de turnos", client_acquisition: "Captación de clientes",
      retention_1_2m: "Clientes que regresan a los 1-2 meses", commission_by_staff: "Comisiones por integrante",
      revenue_by_staff: "Ingresos por estilista", visits_by_staff: "Visitas por estilista", staff_rev_share: "Reparto de ingresos",
      avg_ticket_trend: "Tendencia del ticket promedio", best_clients: "Mejores clientes por gasto", unit: "Unidades",
      done: "Hecho", booked: "Reservado", export_csv: "Exportar CSV", from_records: "Generado con tus registros locales",
      weekday: "Día", week: "Semana", n_clients: "Clientes", revenue_trend: "Tendencia de ingresos", conversion: "Conversión de turnos",
      analytics_builder: "Constructor de analíticas personalizadas",
      analytics_builder_note: "Crea tus propios gráficos al instante: elige una métrica, agrúpala, compara, filtra y elige el gráfico. Guarda las consultas que quieras conservar.",
      query_result: "Resultado de la consulta", saved_queries: "Consultas guardadas", run: "Ejecutar",
      save_query: "Guardar consulta", clear_all: "Borrar todas las guardadas", no_results: "Ningún dato coincide con esta consulta",
      no_saved_queries: "Aún no hay consultas guardadas. Crea una arriba y presiona Guardar consulta.",
      top_n: "Top N filas", export_result: "Exportar resultado",
      metric: "Métrica", group_by: "Agrupar por", compare: "Comparar", chart_type: "Gráfico", period: "Período",
      filter_staff: "Filtro estilista", filter_gender: "Filtro género", filter_payment: "Filtro pago", filter_none: "Todos",
      metric_revenue: "Ingresos", metric_visits: "Visitas", metric_avg_ticket: "Ticket promedio",
      metric_returning: "Visitas recurrentes", metric_new_clients: "Clientes nuevos",
      metric_product_qty: "Productos vendidos", metric_commission: "Comisiones",
      dim_day: "Día", dim_week: "Semana", dim_month: "Mes", dim_weekday: "Día de semana",
      dim_staff: "Estilista", dim_service: "Servicio", dim_product: "Producto",
      dim_payment: "Pago", dim_gender: "Género", dim_client: "Cliente",
      compare_none: "Sin comparación", compare_new_ret: "Nuevos vs recurrentes",
      compare_payment: "Por pago", compare_gender: "Por género", compare_staff: "Por estilista",
      compare_group: "Por grupo de servicio",
      chart_auto: "Auto", chart_bars: "Barras", chart_line: "Línea", chart_donut: "Donut",
      chart_bars_h: "Barras horizontales", chart_heatmap: "Mapa de calor (día x semana)",
      period_all: "Todos los registros", period_custom: "Rango personalizado", from_date: "Desde", to_date: "Hasta",
      custom_range_note: "Las analíticas se agrupan por día (hasta 45 días) o por semana para rangos más largos.",
      starter_packs: "Paquetes de ejemplo", all_packs: "Todos los paquetes", other: "Otros",
      sec_data: "Datos y respaldo",
      data_note: "Exporta, importa y administra tus registros locales.",
      data_backup: "Respaldo", data_backup_desc: "Descarga todos los registros en un archivo JSON para restaurarlos después.",
      data_restore: "Restaurar", data_import_hint: "Elige un archivo de respaldo descargado antes y restáuralo.",
      data_pick_file: "Elige un archivo de respaldo primero", data_bad_file: "Ese archivo no es un respaldo válido de Lumiere",
      data_restored: "Respaldo restaurado", data_reset: "Restablecer datos de demo",
      data_reset_desc: "Descarta los datos actuales y restaura el dataset de demo original.",
      data_reset_confirm: "Esto borrará todos los registros actuales. ¿Continuar?",
      data_export_md: "Exportar registros (Markdown)",
      data_export_clients: "Clientes CSV", data_export_staff: "Equipo CSV", data_export_products: "Productos CSV",
      appt_date: "Fecha", appt_total: "Total",
      appt_status_noshow: "Inasistencia", appt_status_cancelled: "Cancelado",
      appt_need_date_time: "Elige una fecha y una hora", appt_outside_hours: "Fuera del horario de atención",
      appt_conflict: "Ese horario ya está reservado para este/a estilista",
      today_schedule: "Agenda de hoy", reorder_list: "Lista de reposición", restock: "Reponer",
      sec_care: "Atención al cliente",
      care_note: "Re-engagement, lista de ausencias y tus clientes más valiosos.",
      care_due_title: "Deben volver", care_last_visit: "Última visita", care_days_since: "Días desde",
      care_none_due: "Todos visitaron recientemente",
      care_noshow_title: "Lista de ausencias", care_noshows: "Ausencias", care_none_noshow: "Sin ausencias registradas",
      care_vip_title: "Clientes VIP",
      metric_services_rev: "Ingresos por servicios", metric_products_rev: "Ingresos por productos",
      metric_returning_rate: "Tasa de regreso", metric_avg_frequency: "Visitas promedio por cliente",
      receptionist_access: "Acceso de recepción",
      receptionist_access_note: "Elige qué secciones pueden abrir los recepcionistas.",
      delete_confirm: "¿Eliminar este elemento?", deleted: "Eliminado",
      restocked: "Stock actualizado", data_reset_done: "Datos de demo restaurados",
      nl_title: "Haz una pregunta", nl_placeholder: 'p. ej. "Ingresos por servicio este mes"',
      nl_run: "Preguntar", nl_mic: "Voz", nl_listening: "Escuchando...",
      nl_voice_unsupported: "La entrada de voz no es compatible con este navegador",
      nl_error: "No se pudo iniciar la entrada de voz",
      nl_unknown: "No entendí eso. Probá con uno de estos:",
      nl_today: "hoy", nl_from_to: "del {from} al {to}"
    }
  },

  services: {
    "mens-cut":       { name_en: "Men's cut",         name_es: "Corte hombre",          group: "hair",   price_ars: 12000 },
    "womens-cut":     { name_en: "Women's cut",       name_es: "Corte mujer",           group: "hair",   price_ars: 18000 },
    "clipper-cut":    { name_en: "Clipper cut",       name_es: "Corte máquina",         group: "hair",   price_ars: 10000 },
    "fade":           { name_en: "Fade",              name_es: "Degradado",             group: "hair",   price_ars: 15000 },
    "mens-color":     { name_en: "Men's color",       name_es: "Color hombre",          group: "hair",   price_ars: 16000 },
    "womens-color":   { name_en: "Full color",        name_es: "Color completo",        group: "hair",   price_ars: 40000 },
    "highlights":     { name_en: "Highlights",        name_es: "Mechas",                group: "hair",   price_ars: 55000 },
    "balayage":       { name_en: "Balayage",          name_es: "Balayage",              group: "hair",   price_ars: 60000 },
    "keratin":        { name_en: "Keratin treatment", name_es: "Alisado de keratina",   group: "hair",   price_ars: 70000 },
    "olaplex":        { name_en: "Olaplex treatment", name_es: "Tratamiento olaplex",   group: "hair",   price_ars: 25000 },
    "scalp":          { name_en: "Scalp treatment",   name_es: "Tratamiento capilar",   group: "hair",   price_ars: 20000 },
    "mens-manicure":  { name_en: "Men's manicure",    name_es: "Manicuría hombre",      group: "nails",  price_ars: 10000 },
    "womens-manicure":{ name_en: "Classic manicure",  name_es: "Manicuría clásica",     group: "nails",  price_ars: 15000 },
    "gel-manicure":   { name_en: "Gel manicure",      name_es: "Manicuría en gel",      group: "nails",  price_ars: 22000 },
    "acrylic":        { name_en: "Acrylic nails",     name_es: "Uñas esculpidas",       group: "nails",  price_ars: 35000 },
    "dip":            { name_en: "Dip powder",        name_es: "Uñas en polvo",         group: "nails",  price_ars: 28000 },
    "mens-pedicure":  { name_en: "Men's pedicure",    name_es: "Pedicuría hombre",      group: "nails",  price_ars: 12000 },
    "womens-pedicure":{ name_en: "Classic pedicure",  name_es: "Pedicuría clásica",     group: "nails",  price_ars: 18000 },
    "spa-pedicure":   { name_en: "Spa pedicure",      name_es: "Pedicuría spa",         group: "nails",  price_ars: 30000 },
    "mens-facial":    { name_en: "Men's facial",      name_es: "Limpieza facial hombre",group: "beauty", price_ars: 25000 },
    "womens-facial":  { name_en: "Facial",            name_es: "Limpieza facial",       group: "beauty", price_ars: 35000 },
    "waxing":         { name_en: "Waxing",            name_es: "Depilación",            group: "beauty", price_ars: 15000 },
    "lash-lift":      { name_en: "Lash lift",         name_es: "Lifting de pestañas",   group: "beauty", price_ars: 20000 },
    "lash-ext":       { name_en: "Lash extensions",   name_es: "Extensiones de pestañas",group: "beauty", price_ars: 45000 },
    "brow-shaping":   { name_en: "Brow shaping",      name_es: "Diseño de cejas",       group: "beauty", price_ars: 12000 },
    "brow-tint":      { name_en: "Brow tint",         name_es: "Tintado de cejas",      group: "beauty", price_ars: 10000 },
    "brow-lamination":{ name_en: "Brow lamination",   name_es: "Laminado de cejas",     group: "beauty", price_ars: 18000 }
  },

  products: {
    "shampoo-250ml":  { name_en: "Shampoo 250ml",     name_es: "Shampoo 250ml",     price_ars: 8500,  stock: 24, reorder: 6 },
    "conditioner":    { name_en: "Conditioner 250ml", name_es: "Acondicionador",    price_ars: 9000,  stock: 18, reorder: 6 },
    "serum-30ml":     { name_en: "Hair serum 30ml",   name_es: "Sérum capilar 30ml",price_ars: 18000, stock: 12, reorder: 4 },
    "gel-polish":     { name_en: "Gel polish",        name_es: "Esmalte en gel",    price_ars: 12000, stock: 30, reorder: 8 },
    "cuticle-oil":    { name_en: "Cuticle oil",       name_es: "Aceite de cutícula",price_ars: 8000,  stock: 3,  reorder: 5 },
    "hair-mask":      { name_en: "Hair mask",         name_es: "Mascarilla capilar",price_ars: 20000, stock: 9,  reorder: 4 }
  },

  staff: [
    { id: "owner-001",        name: "Owner",                 role: "owner",        shift: "" },
    { id: "admin-001",        name: "Administrator",         role: "administrator",shift: "" },
    { id: "stylist-001-amara", name: "Amara",                role: "stylist",      shift: "" },
    { id: "stylist-002-carlos",name: "Carlos",               role: "stylist",      shift: "" },
    { id: "assistant-001-lena",name: "Lena",                 role: "assistant",    shift: "" },
    { id: "assistant-002-diego",name: "Diego",               role: "assistant",    shift: "" },
    { id: "receptionist-001-mary", name: "Mary",             role: "receptionist", shift: "morning" },
    { id: "receptionist-002-sofia", name: "Sofia",           role: "receptionist", shift: "afternoon" }
  ],

  commissionRates: {
    "stylist-001-amara":  { service: 30, product: 10 },
    "stylist-002-carlos": { service: 35, product: 12 },
    "assistant-001-lena": { service: 15, product: 5 },
    "assistant-002-diego":{ service: 12, product: 5 }
  },

  clients: [
    { id: "0001", name: "Jane Doe",       gender_line: "women", first_visit: "2026-06-05", visits: ["2026-06-05","2026-06-26","2026-07-10","2026-07-24","2026-08-07"] },
    { id: "0002", name: "John Smith",     gender_line: "men",   first_visit: "2026-06-10", visits: ["2026-06-10","2026-07-03","2026-08-12"] },
    { id: "0003", name: "Maria Lopez",    gender_line: "women", first_visit: "2026-06-15", visits: ["2026-06-15","2026-07-20"] },
    { id: "0004", name: "Carlos Garcia",  gender_line: "men",   first_visit: "2026-07-01", visits: ["2026-07-01","2026-08-05"] },
    { id: "0005", name: "Sofia Ramirez",  gender_line: "women", first_visit: "2026-07-08", visits: ["2026-07-08","2026-07-29"] },
    { id: "0006", name: "Luis Fernandez", gender_line: "men",   first_visit: "2026-07-15", visits: ["2026-07-15"] },
    { id: "0007", name: "Ana Torres",     gender_line: "women", first_visit: "2026-07-22", visits: ["2026-07-22","2026-08-11"] },
    { id: "0008", name: "Pablo Diaz",     gender_line: "men",   first_visit: "2026-08-03", visits: ["2026-08-03"] },
    { id: "0009", name: "Lucia Martinez", gender_line: "women", first_visit: "2026-08-06", visits: ["2026-08-06","2026-08-13"] },
    { id: "0010", name: "Diego Ruiz",     gender_line: "men",   first_visit: "2026-08-10", visits: ["2026-08-10"] },
    { id: "0011", name: "Camila Herrera", gender_line: "women", first_visit: "2026-08-12", visits: ["2026-08-12"] },
    { id: "0012", name: "Santiago Moreno",gender_line: "men",   first_visit: "2026-06-18", visits: ["2026-06-18","2026-08-06"] }
  ],

  tickets: [
    { date: "2026-06-05", seq: "001", client: "0001", stylist: "stylist-001-amara", assistant: "assistant-001-lena",
      lines: [{ t: "service", k: "womens-cut", q: 1 }, { t: "service", k: "olaplex", q: 1 }, { t: "product", k: "shampoo-250ml", q: 1 }],
      payments: [{ m: "card", a: 56000 }] },
    { date: "2026-06-10", seq: "002", client: "0002", stylist: "stylist-002-carlos", assistant: "",
      lines: [{ t: "service", k: "mens-cut", q: 1 }, { t: "product", k: "serum-30ml", q: 1 }],
      payments: [{ m: "cash", a: 30000 }] },
    { date: "2026-06-15", seq: "003", client: "0003", stylist: "stylist-001-amara", assistant: "",
      lines: [{ t: "service", k: "womens-manicure", q: 1 }],
      payments: [{ m: "cash", a: 15000 }] },
    { date: "2026-06-18", seq: "004", client: "0012", stylist: "stylist-002-carlos", assistant: "assistant-002-diego",
      lines: [{ t: "service", k: "mens-cut", q: 1 }, { t: "service", k: "fade", q: 1 }],
      payments: [{ m: "card", a: 27000 }] },
    { date: "2026-06-26", seq: "005", client: "0001", stylist: "stylist-001-amara", assistant: "assistant-001-lena",
      lines: [{ t: "service", k: "womens-color", q: 1 }, { t: "product", k: "hair-mask", q: 1 }],
      payments: [{ m: "card", a: 60000 }] },
    { date: "2026-07-01", seq: "001", client: "0004", stylist: "stylist-002-carlos", assistant: "assistant-002-diego",
      lines: [{ t: "service", k: "mens-cut", q: 1 }],
      payments: [{ m: "cash", a: 12000 }] },
    { date: "2026-07-03", seq: "002", client: "0002", stylist: "stylist-001-amara", assistant: "assistant-001-lena",
      lines: [{ t: "service", k: "keratin", q: 1 }, { t: "product", k: "conditioner", q: 1 }],
      payments: [{ m: "card", a: 79000 }] },
    { date: "2026-07-08", seq: "003", client: "0005", stylist: "stylist-001-amara", assistant: "",
      lines: [{ t: "service", k: "brow-lamination", q: 1 }, { t: "service", k: "lash-lift", q: 1 }],
      payments: [{ m: "cash", a: 38000 }] },
    { date: "2026-07-10", seq: "004", client: "0001", stylist: "stylist-001-amara", assistant: "assistant-001-lena",
      lines: [{ t: "service", k: "highlights", q: 1 }],
      payments: [{ m: "card", a: 55000 }] },
    { date: "2026-07-15", seq: "005", client: "0006", stylist: "stylist-002-carlos", assistant: "assistant-002-diego",
      lines: [{ t: "service", k: "mens-facial", q: 1 }, { t: "service", k: "mens-cut", q: 1 }],
      payments: [{ m: "cash", a: 37000 }] },
    { date: "2026-07-20", seq: "006", client: "0003", stylist: "stylist-001-amara", assistant: "",
      lines: [{ t: "service", k: "spa-pedicure", q: 1 }, { t: "service", k: "gel-manicure", q: 1 }],
      payments: [{ m: "mobile", a: 52000 }] },
    { date: "2026-07-22", seq: "007", client: "0007", stylist: "stylist-002-carlos", assistant: "",
      lines: [{ t: "service", k: "womens-facial", q: 1 }, { t: "product", k: "serum-30ml", q: 1 }],
      payments: [{ m: "card", a: 53000 }] },
    { date: "2026-07-24", seq: "008", client: "0001", stylist: "stylist-001-amara", assistant: "assistant-001-lena",
      lines: [{ t: "service", k: "balayage", q: 1 }],
      payments: [{ m: "gift_card", a: 60000 }] },
    { date: "2026-07-29", seq: "009", client: "0005", stylist: "stylist-001-amara", assistant: "",
      lines: [{ t: "service", k: "womens-manicure", q: 1 }, { t: "product", k: "gel-polish", q: 1 }],
      payments: [{ m: "cash", a: 27000 }] },
    { date: "2026-08-03", seq: "001", client: "0008", stylist: "stylist-002-carlos", assistant: "assistant-002-diego",
      lines: [{ t: "service", k: "mens-cut", q: 1 }, { t: "service", k: "scalp", q: 1 }],
      payments: [{ m: "cash", a: 32000 }] },
    { date: "2026-08-05", seq: "002", client: "0004", stylist: "stylist-001-amara", assistant: "assistant-001-lena",
      lines: [{ t: "service", k: "womens-color", q: 1 }, { t: "service", k: "olaplex", q: 1 }],
      payments: [{ m: "card", a: 65000 }] },
    { date: "2026-08-06", seq: "003", client: "0012", stylist: "stylist-002-carlos", assistant: "assistant-002-diego",
      lines: [{ t: "service", k: "mens-cut", q: 1 }, { t: "product", k: "serum-30ml", q: 1 }],
      payments: [{ m: "cash", a: 30000 }] },
    { date: "2026-08-06", seq: "004", client: "0009", stylist: "stylist-001-amara", assistant: "assistant-001-lena",
      lines: [{ t: "service", k: "womens-manicure", q: 1 }, { t: "service", k: "womens-pedicure", q: 1 }],
      payments: [{ m: "mobile", a: 33000 }] },
    { date: "2026-08-07", seq: "005", client: "0001", stylist: "stylist-001-amara", assistant: "assistant-001-lena",
      lines: [{ t: "service", k: "womens-cut", q: 1 }, { t: "service", k: "olaplex", q: 1 }, { t: "product", k: "hair-mask", q: 1 }],
      payments: [{ m: "card", a: 63000 }] },
    { date: "2026-08-10", seq: "001", client: "0010", stylist: "stylist-002-carlos", assistant: "assistant-002-diego",
      lines: [{ t: "service", k: "mens-cut", q: 1 }, { t: "service", k: "brow-shaping", q: 1 }],
      payments: [{ m: "cash", a: 24000 }] },
    { date: "2026-08-11", seq: "002", client: "0007", stylist: "stylist-001-amara", assistant: "",
      lines: [{ t: "service", k: "highlights", q: 1 }, { t: "service", k: "womens-cut", q: 1 }],
      payments: [{ m: "card", a: 73000 }] },
    { date: "2026-08-12", seq: "003", client: "0002", stylist: "stylist-002-carlos", assistant: "assistant-002-diego",
      lines: [{ t: "service", k: "mens-cut", q: 1 }, { t: "product", k: "shampoo-250ml", q: 1 }],
      payments: [{ m: "cash", a: 20500 }] },
    { date: "2026-08-12", seq: "004", client: "0011", stylist: "stylist-001-amara", assistant: "assistant-001-lena",
      lines: [{ t: "service", k: "lash-ext", q: 1 }],
      payments: [{ m: "card", a: 45000 }] },
    { date: "2026-08-13", seq: "001", client: "0009", stylist: "stylist-001-amara", assistant: "assistant-001-lena",
      lines: [{ t: "service", k: "gel-manicure", q: 1 }, { t: "product", k: "gel-polish", q: 1 }],
      payments: [{ m: "card", a: 34000 }] },
    { date: "2026-08-13", seq: "002", client: "0001", stylist: "stylist-001-amara", assistant: "assistant-001-lena",
      lines: [{ t: "service", k: "keratin", q: 1 }, { t: "product", k: "hair-mask", q: 1 }],
      payments: [{ m: "cash", a: 90000 }] },
    { date: "2026-08-13", seq: "003", client: "0010", stylist: "stylist-002-carlos", assistant: "assistant-002-diego",
      lines: [{ t: "service", k: "clipper-cut", q: 1 }],
      payments: [{ m: "mobile", a: 10000 }] },
    { date: "2026-08-13", seq: "004", client: "0012", stylist: "stylist-002-carlos", assistant: "assistant-002-diego",
      lines: [{ t: "service", k: "fade", q: 1 }, { t: "product", k: "serum-30ml", q: 1 }],
      payments: [{ m: "cash", a: 33000 }] },
    { date: "2026-08-13", seq: "005", client: "0005", stylist: "stylist-001-amara", assistant: "",
      lines: [{ t: "service", k: "brow-tint", q: 1 }, { t: "service", k: "womens-pedicure", q: 1 }],
      payments: [{ m: "card", a: 28000 }] }
  ],

  noShows: {
    "2026-08-10": 1, "2026-08-11": 0, "2026-08-12": 1, "2026-08-13": 1
  },

  openingHours: {
    open: "08:00",
    close: "21:00",
    days: ["mon", "tue", "wed", "thu", "fri", "sat"]
  },

  appointments: [
    { id: "app-001", date: "2026-08-10", time: "09:00", client: "0001", stylist: "stylist-001-amara", service: "womens-color", status: "done" },
    { id: "app-002", date: "2026-08-10", time: "10:00", client: "0002", stylist: "stylist-002-carlos", service: "mens-cut", status: "done" },
    { id: "app-003", date: "2026-08-10", time: "17:00", client: "0010", stylist: "stylist-002-carlos", service: "fade", status: "no-show" },
    { id: "app-004", date: "2026-08-11", time: "11:00", client: "0005", stylist: "stylist-001-amara", service: "lash-lift", status: "done" },
    { id: "app-005", date: "2026-08-11", time: "16:00", client: "0007", stylist: "stylist-002-carlos", service: "womens-facial", status: "done" },
    { id: "app-006", date: "2026-08-12", time: "09:30", client: "0008", stylist: "stylist-002-carlos", service: "mens-cut", status: "done" },
    { id: "app-007", date: "2026-08-12", time: "14:00", client: "0011", stylist: "stylist-001-amara", service: "lash-ext", status: "done" },
    { id: "app-008", date: "2026-08-12", time: "18:00", client: "0003", stylist: "stylist-001-amara", service: "spa-pedicure", status: "no-show" },
    { id: "app-009", date: "2026-08-13", time: "10:00", client: "0009", stylist: "stylist-001-amara", service: "gel-manicure", status: "done" },
    { id: "app-010", date: "2026-08-13", time: "11:30", client: "0001", stylist: "stylist-001-amara", service: "keratin", status: "done" },
    { id: "app-011", date: "2026-08-13", time: "13:00", client: "0010", stylist: "stylist-002-carlos", service: "clipper-cut", status: "done" },
    { id: "app-012", date: "2026-08-13", time: "15:00", client: "0012", stylist: "stylist-002-carlos", service: "fade", status: "done" },
    { id: "app-013", date: "2026-08-13", time: "16:30", client: "0005", stylist: "stylist-001-amara", service: "brow-tint", status: "done" },
    { id: "app-014", date: "2026-08-14", time: "10:00", client: "0004", stylist: "stylist-001-amara", service: "womens-color", status: "booked" },
    { id: "app-015", date: "2026-08-14", time: "12:00", client: "0006", stylist: "stylist-002-carlos", service: "mens-facial", status: "booked" },
    { id: "app-016", date: "2026-08-14", time: "17:30", client: "0002", stylist: "stylist-002-carlos", service: "mens-cut", status: "booked" },
    { id: "app-017", date: "2026-08-15", time: "09:00", client: "0007", stylist: "stylist-001-amara", service: "highlights", status: "booked" },
    { id: "app-018", date: "2026-08-15", time: "13:00", client: "0009", stylist: "stylist-001-amara", service: "womens-pedicure", status: "booked" },
    { id: "app-019", date: "2026-08-15", time: "15:00", client: "0011", stylist: "stylist-001-amara", service: "acrylic", status: "booked" },
    { id: "app-020", date: "2026-08-15", time: "18:00", client: "0008", stylist: "stylist-002-carlos", service: "brow-shaping", status: "booked" }
  ]
};
